import mongoose, { Document, Schema } from "mongoose";

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

export type Pillar =
  | "menstrual_hygiene"
  | "environment"
  | "digital_skills"
  | "life_skills";
export type AgeGroup = "10-13" | "14-18" | "both";

export interface IChunk extends Document {
  _id: mongoose.Types.ObjectId;
  text: string; // raw chunk text (400-token window)
  pillar: Pillar;
  sessionNumber: string; // e.g. "1.3"
  sessionTitle: string; // e.g. "Menstrual Cycle Science"
  ageGroup: AgeGroup;
  topicTags: string[]; // e.g. ["cramps", "prostaglandins", "pain relief"]
  source: string; // human-readable citation shown in UI
  embedding: number[]; // 384-dim float[] from HuggingFace all-MiniLM-L6-v2
  checksum: string; // md5 of text — used to deduplicate on re-ingest
  createdAt: Date;
  updatedAt: Date;
}

// ─────────────────────────────────────────────
// Schema
// ─────────────────────────────────────────────

const ChunkSchema = new Schema<IChunk>(
  {
    text: {
      type: String,
      required: [true, "Chunk text is required"],
    },
    pillar: {
      type: String,
      enum: [
        "menstrual_hygiene",
        "environment",
        "digital_skills",
        "life_skills",
      ],
      required: [true, "Pillar is required"],
    },
    sessionNumber: {
      type: String,
      required: [true, "Session number is required"],
    },
    sessionTitle: {
      type: String,
      required: [true, "Session title is required"],
    },
    ageGroup: {
      type: String,
      enum: ["10-13", "14-18", "both"],
      default: "both",
    },
    topicTags: { type: [String], default: [] },
    source: { type: String, required: true },

    // ── Vector embedding ──────────────────────────────────────────────
    // Generated by HuggingFace Inference API (all-MiniLM-L6-v2, 384-dim)
    // Falls back to keyword search if HF_API_KEY is missing
    embedding: {
      type: [Number],
      default: [],
    },

    checksum: { type: String, required: true },
  },
  { timestamps: true },
);

// ─────────────────────────────────────────────
// Indexes
// ─────────────────────────────────────────────

ChunkSchema.index({ pillar: 1, ageGroup: 1 });
ChunkSchema.index({ topicTags: 1 });
ChunkSchema.index({ checksum: 1 }, { unique: true });

// Atlas Vector Search index — create this in the Atlas UI:
// Collection : chunks
// Index name : chunk_vector_index
// Field      : embedding   (type: vector, dimensions: 384, similarity: cosine)

export default mongoose.model<IChunk>("Chunk", ChunkSchema);
